### PR TITLE
skip web api add call

### PR DESCRIPTION
**Pull request by Behnam-Emamian**

### CODE REVIEW

**Review by Mewriick — APPROVED** [review]
Thanks, for new feature

**Comment by Behnam-Emamian** [comment]
Thanks for accepting the request, I was on hurry and could not post the reason.

I am developing an application which saves all data in browser's indexeddb, so there is not any web api for call and because of that I have disable it.

**Comment by Behnam-Emamian** [comment]
I have plan to add some new features like
Does not showing the primaryid in webform
showing the url in grid
show phone number in grid, I mean in mobile, user can click and call.

**Comment by Mewriick** [comment]
> I have plan to add some new features like
> Does not showing the primaryid in webform
> showing the url in grid
> show phone number in grid, I mean in mobile, user can click and call.

Very nice ideas. I am very glad that you helping me pushing this component forward.

**Pull request merged**
